# Telecom Customer Churn Project

**Importing pandas for data manipulation and analysis**

**Importing numpy for numerical operations**

In [81]:
import pandas as pd
import numpy as np

**Reading the Excel file into a pandas DataFrame named df**

In [82]:
df = pd.read_excel('Churn_Unclean_Project.xlsx')

**Just to preview the data displaying the first 5 rows of the DataFrame**

In [83]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

**We will check column names, data types, and non-null counts for each column**

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 76.3 KB

**Generating summary statistics (count, mean, std, min, max, etc.) for numeric columns**

In [85]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

**Checking the number of rows and columns in the DataFrame**

In [86]:
df.shape

(542, 18)

**Checking the number of missing values in each column**

In [87]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

**Checking the number of duplicate rows in the DataFrame**

In [88]:
df.duplicated().sum()

np.int64(7)

**Removing duplicate rows from the DataFrame and updating it directly to orignal file**

In [89]:
df.drop_duplicates(inplace=True)

**Re-checking the number of duplicate rows to confirm they've been removed**

In [90]:
df.duplicated().sum()

np.int64(0)

**Replacing inconsistent missing values with a standard NaN (This helps standardize missing values in a DataFrame because pandas recognizes NaN as a missing value.)**

In [91]:
df.replace(['N/A', 'NULL', ''], np.nan, inplace = True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

**Stripping extra whitespace from text (string) columns**

**We will remove unwanted leading and trailing spaces from text values so that data is clean and consistent.**

In [92]:
df = df.apply(lambda x:x.str.strip() if x.dtype == "str" else x)

**Standardizing values to title case**

In [93]:
df["Customer_Name"] = df["Customer_Name"].str.title()
df["State"] = df["State"].str.title()
df["City"] = df["City"].str.title()
df["Subscription_Type"] = df["Subscription_Type"].str.title()
df["Contract_Type"] = df["Contract_Type"].str.title()
df["Churn"] = df["Churn"].str.title()
df["Contract_Type"] = df["Contract_Type"].str.title()
df["Gender"] = df["Gender"].str.title()
df["Payment_Method"] = df["Payment_Method"].str.title()
df["Internet_Service"] = df["Internet_Service"].str.title()
df["Tech_Support"] = df["Tech_Support"].str.title()
df["Senior_Citizen"] = df["Senior_Citizen"].str.title()
df["Dependents"] = df["Dependents"].str.title()

**Checking if any lower case value remains (any 2 random columns)**

In [94]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [95]:
df["Tech_Support"].value_counts()

Tech_Support
No     271
Yes    253
Name: count, dtype: int64

**Removing invalid ages above 100 years**

In [96]:
df = df[(df['Age'] >=18) & (df['Age'] <=100)]

**Removing Negative values in charges column**

In [97]:
df = df[df["Monthly_Charges"]>= 0]
df = df[df["Total_Charges"]>= 0]

In [98]:
df.shape

(492, 18)

**Converting 'Last_Interaction_Date' to a proper datetime format and convert invalid values to NaT (missing date/time)**

**We are doing this because dates stored as plain text cannot be reliably sorted, filtered, compared, or used for date calculations; converting them to datetime lets pandas perform these operations correctly**

**errors="coerce" prevents invalid dates from causing errors by converting them to NaT.**

In [99]:
df["Last_Interaction_Date"] = pd.to_datetime(df["Last_Interaction_Date"], errors = 'coerce')

**Filling missing values**

In [100]:
df["Tech_Support"]=df["Tech_Support"].fillna("No")

df["Payment_Method"]=df["Payment_Method"].fillna("Unknown")

df["Monthly_Charges"]=df["Monthly_Charges"].fillna(df['Monthly_Charges'].mean())

df["Tenure_Months"]=df["Tenure_Months"].fillna(df['Tenure_Months'].mean())

df['Age'] = df['Age'].fillna(df['Age'].mean())

**Starting Feature Engineering here since the data is now clean, and we need to derive business-relevant metrics that the raw columns don't directly provide. We will be answering our questions here:**

First we wil find out Customer Lifetime Value (how much a customer pays

In [101]:
df['Customer_Value'] = df["Monthly_Charges"] *df["Tenure_Months"]

**Let's make a column for monthly revenue which will be same as Monthly_Charges.**

In [102]:
df["Monthly_Revenue"] = df["Monthly_Charges"]

**We wil now group the custromers based on their Tenure (0-12, 13-24, 25-48, 49-72)**

In [103]:
bins=[0,12,24,48,72]
label = labels = ["0-12 Months","13-24 Months","25-48 Months","49-72 Months"]
df["Tenure_Group"] = pd.cut(df["Tenure_Months"], bins = bins, labels = label)

**Adding a senior flag column using numpy where functions.**

In [104]:
df["Senior_Flag"]=np.where(df["Age"]>=60,"Senior","Adult")

**Adding a churn column now.**

In [105]:
df["Churn_Flag"]=df["Churn"].map({"Yes":1,"No":0})

In [106]:
df.info()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   489 non-null    str
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  178 non-null    datetime64[us]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 88.9 KB

**As we can see above, the Last_Interaction_Date column still has plaenty missing values. To correct it, we will add mean values as we did earlier.**

In [107]:
df["Last_Interaction_Date"] = df["Last_Interaction_Date"].fillna(df["Last_Interaction_Date"].median())

**Let's recheck it.**

In [108]:
df.info()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   489 non-null    str
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  492 non-null    datetime64[us]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 88.9 KB

**As the final step, we will export the cleaned data for further analysis.
Exporting the cleaned DataFrame to a new CSV file**

In [109]:
df.to_csv("Clean_Churn_Data.csv", index=False)

**Importing data in MySQL**

In [110]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:newpassword@localhost/churndb")

In [111]:
df.to_sql(
name="customer_churn",
con=engine,
if_exists="replace",
index=False
)

492